/* comp-decomp.h generated by valac 0.16.0, the Vala compiler, do not modify */


#ifndef __COMP_DECOMP_H__
#define __COMP_DECOMP_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS



void comp_decomp_comprime (const gchar* s, gchar** cs);


G_END_DECLS

#endif
